[REFACTOR] chapter 4-6
computer-topic/mid-exam pull request #55
Opened 2024-10-22 15:44 UTC by dpfls0922

### 문제라고 생각한 부분
- 알고리즘에 대한 정보를 알려주는 주석과, 불필요한 주석이 혼재됨
- 함수가 너무 긺
- 의도가 전달이 안됨

### 리팩터링 요소
- 기능별로 함수 분리
- 불필요한 주석 제거

2024-10-22 16:04 UTC, sung-silver requested changes
리뷰가 좀 많아요 헤헤..

2024-10-22 16:04 UTC, sung-silver commented on chapter4/dpfls/refactor-chpater4-6.java
> + */
좋은 주석인데 전 ..날려버렸네요 아호ㅜ

2024-10-22 16:04 UTC, sung-silver commented on chapter4/dpfls/refactor-chpater4-6.java
> +      }
이런 방법도 좋은 것 같네요!

2024-10-22 16:04 UTC, sung-silver commented on chapter4/dpfls/refactor-chpater4-6.java
> +      return initializePrimeNumbers(primeCount);
혹시 이 primeCount는 어디서 온 친구일까요??

2024-10-22 16:04 UTC, sung-silver commented on chapter4/dpfls/refactor-chpater4-6.java
> +      int primeCount;
매개변수랑 동일한 이름으로 필드를 선언하신 이유가 있을까요??

2024-10-22 16:04 UTC, sung-silver commented on chapter4/dpfls/refactor-chpater4-6.java
> +        if (isUncrossedNumber(i)) {
mark와 cross의 차이점이 무엇인가요?! true, false 체크의 개념이라면 하나로 단어를 통일하는게 좋을 것 같아요!

2024-10-22 16:09 UTC, dpfls0922 commented on chapter4/dpfls/refactor-chpater4-6.java
> +      int primeCount;
이것도 다시 re-refactor하는 과정에서 제거를 못했네요오.ㅇ..

2024-10-22 16:09 UTC, dpfls0922 commented on chapter4/dpfls/refactor-chpater4-6.java
> +        if (isUncrossedNumber(i)) {
좋은 아이디어 감사합니다!

2024-10-22 16:11 UTC, dpfls0922 commented on chapter4/dpfls/refactor-chpater4-6.java
> +      return initializePrimeNumbers(primeCount);
리팩하는 과정에서 지워졌나봅니다..

2024-10-22 21:00 UTC, haesa commented on chapter4/dpfls/refactor-chpater4-6.java
> +        return maxValue >= 2;
2를 소수의 최솟값이라는 의미로 MIN_PRIME 상수로 분리해보는 것도 좋을 것 같아요 :)

2024-10-22 21:00 UTC, haesa commented on chapter4/dpfls/refactor-chpater4-6.java
> +    }
해당 메서드는 멤버 변수 primeFlags의 값을 초기화하는 로직이라 return은 불필요해 보여요!

2024-10-23 01:34 UTC, dpfls0922 commented on chapter4/dpfls/refactor-chpater4-6.java
> +    }
반영했습니다!

2024-10-23 01:44 UTC, merged